variable "KEY_NAME" {}
variable "PATH_TO_PUBLIC_KEY" {}
variable "SG_VPC_ID" {}
variable "SG_NAME" {}
variable "SG_DESCRIPTION" {}
variable "AMI_ID" {}
variable "INSTANCE_TYPE" {}
variable "INSTANCE_SUBNET_ID" {}
variable "INSTANCE_NAME" {}